# Generated by Django 5.1.6 on 2025-04-26 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя магазина')),
                ('regex_name', models.CharField(max_length=100, verbose_name='Имя из url')),
                ('main_url', models.URLField(blank=True, verbose_name='URL главной страницы')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя продукта')),
                ('latest_price', models.IntegerField(verbose_name='Последняя цена')),
                ('url', models.URLField(verbose_name='URL')),
                ('ref_url', models.URLField(verbose_name='Ref-URL')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления продукта')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обновления продукта')),
                ('subs', models.ManyToManyField(to='blog.author', verbose_name='Подписчики продукта')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='price_checker.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'indexes': [models.Index(fields=['name'], name='price_check_name_2a19a7_idx')],
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='tags',
            field=models.ManyToManyField(to='price_checker.tag'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('added_time', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_checker.product', verbose_name='Имя продукта')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ['added_time'],
                'indexes': [models.Index(fields=['product'], name='price_check_product_31dcaf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop'], name='price_check_shop_id_962424_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['name'], name='price_check_name_c38d8c_idx'),
        ),
    ]
