# Generated by Django 5.1.6 on 2025-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-added_time'], 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AddField(
            model_name='product',
            name='first_price',
            field=models.IntegerField(default=1, verbose_name='Первая цена'),
            preserve_default=False,
        ),
    ]
