# Generated by Django 5.1.6 on 2025-03-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0002_rename_link_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
