# Generated by Django 5.1.6 on 2025-05-22 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0003_remove_product_subs_product_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['url'], name='price_check_url_dd67b0_idx'),
        ),
    ]
