# Generated by Django 5.1.6 on 2025-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0004_product_price_check_url_dd67b0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='repeated',
            field=models.BooleanField(default=False),
        ),
    ]
