# Generated by Django 5.1.6 on 2025-03-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0005_alter_price_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['added_time']},
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
