# Generated by Django 5.1.6 on 2025-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0005_product_repeated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_notified_price',
            field=models.IntegerField(null=True, verbose_name='Цена уведомления пользователя'),
        ),
    ]
