# Generated by Django 5.1.6 on 2025-03-14 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_author_options_alter_author_nickname'),
        ('price_checker', '0006_alter_price_options_product_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['added_time'], 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='price',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_checker.product', verbose_name='Имя продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='blog.author', verbose_name='Никнейм автора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(null=True, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='latest_price',
            field=models.IntegerField(verbose_name='Последняя цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(blank=True, max_length=100, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
