# Generated by Django 5.1.6 on 2025-03-16 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_author_options_alter_author_nickname'),
        ('price_checker', '0007_alter_price_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='DeletedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена удаленного продукта')),
                ('added_time', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен удаленный продукт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_checker.product', verbose_name='Имя удаленного продукта')),
            ],
            options={
                'verbose_name': 'Цена удаленного продукта',
                'verbose_name_plural': 'Цены удаленного продукта',
                'ordering': ['added_time'],
            },
        ),
        migrations.CreateModel(
            name='DeletedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя удаленного продукта')),
                ('shop', models.CharField(blank=True, max_length=100, verbose_name='Магазин удаленного продукта')),
                ('categoty', models.CharField(blank=True, max_length=100, verbose_name='Категория удаленного продукта')),
                ('latest_price', models.IntegerField(verbose_name='Последняя цена удаленного продукта')),
                ('url', models.URLField(verbose_name='URL удаленного продукта')),
                ('image', models.URLField(null=True, verbose_name='Картинка удаленного продукта')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletedproducts', to='blog.author', verbose_name='Никнейм автора удаленного продукта')),
            ],
            options={
                'verbose_name': 'Удаленный продукт',
                'verbose_name_plural': 'Удаленные продукты',
                'ordering': ['-id'],
            },
        ),
    ]
