# Generated by Django 5.1.6 on 2025-03-16 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0009_rename_categoty_deletedproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_checker.deletedproduct', verbose_name='Имя удаленного продукта'),
        ),
    ]
