# Generated by Django 5.1.6 on 2025-03-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0010_alter_deletedprice_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedproduct',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='DeletedPrice',
        ),
        migrations.DeleteModel(
            name='DeletedProduct',
        ),
    ]
