# Generated by Django 5.1.6 on 2025-03-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0014_alter_product_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
