# Generated by Django 5.1.6 on 2025-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0015_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
