# Generated by Django 5.1.6 on 2025-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0017_alter_product_created_alter_product_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
