# Generated by Django 5.1.6 on 2025-03-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0018_alter_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
