# Generated by Django 5.1.6 on 2025-03-18 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0019_remove_product_image_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обновления продукта'),
        ),
    ]
