# Generated by Django 5.1.6 on 2025-03-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0020_alter_product_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя магазина')),
                ('regex_name', models.CharField(max_length=100, verbose_name='Имя из url')),
                ('main_url', models.URLField(blank=True, verbose_name='URL главной страницы')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
