# Generated by Django 5.1.6 on 2025-03-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0021_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
    ]
