# Generated by Django 5.1.6 on 2025-03-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0024_tag_shop_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
