# Generated by Django 5.1.6 on 2025-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0025_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref_url',
            field=models.URLField(default='', verbose_name='Ref-URL'),
            preserve_default=False,
        ),
    ]
