# Generated by Django 5.1.6 on 2025-03-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_author_options_alter_author_nickname'),
        ('price_checker', '0026_product_ref_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['product'], name='price_check_product_31dcaf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'author'], name='price_check_shop_id_2f705b_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['name'], name='price_check_name_c38d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='price_check_name_2a19a7_idx'),
        ),
    ]
