# Generated by Django 5.1.6 on 2025-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0028_wbseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя бренда WB')),
                ('wb_id', models.CharField(max_length=100, verbose_name='ID бренда WB')),
                ('main_url', models.URLField(blank=True, verbose_name='URL главной страницы')),
                ('catalog_count', models.IntegerField(verbose_name='Всего товаров в каталоге бренда')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'indexes': [models.Index(fields=['name'], name='price_check_name_072ac1_idx')],
            },
        ),
    ]
