# Generated by Django 5.1.6 on 2025-03-26 17:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_author_subscription'),
        ('price_checker', '0029_wbbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта WB')),
                ('artikul', models.CharField(max_length=100, verbose_name='Артикул продукта WB')),
                ('latest_price', models.IntegerField(verbose_name='Последняя цена')),
                ('wb_cosh', models.BooleanField(default=True)),
                ('url', models.URLField(verbose_name='URL')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления продукта WB')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обновления продукта WB')),
                ('authors', models.ManyToManyField(to='blog.author', verbose_name='Никнеймы авторов')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_checker.wbbrand', verbose_name='Бренд продукта WB')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_checker.wbseller', verbose_name='Продавец продукта WB')),
            ],
            options={
                'verbose_name': 'Продукт WB',
                'verbose_name_plural': 'Продукты WB',
                'ordering': ['-updated'],
            },
        ),
    ]
