# Generated by Django 5.1.6 on 2025-03-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0030_wbproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена продукта WB')),
                ('added_time', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_checker.wbproduct', verbose_name='Продукт WB')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ['added_time'],
                'indexes': [models.Index(fields=['product'], name='price_check_product_875053_idx')],
            },
        ),
    ]
