# Generated by Django 5.1.6 on 2025-03-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0031_wbprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='wbprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wbproduct',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='wbproduct',
            name='seller',
        ),
        migrations.DeleteModel(
            name='WBBrand',
        ),
        migrations.DeleteModel(
            name='WBPrice',
        ),
        migrations.DeleteModel(
            name='WBProduct',
        ),
        migrations.DeleteModel(
            name='WBSeller',
        ),
    ]
