# Generated by Django 5.1.6 on 2025-04-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_author_subscription'),
        ('price_checker', '0032_remove_wbproduct_brand_remove_wbprice_product_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='price_check_shop_id_2f705b_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='subs',
            field=models.ManyToManyField(to='blog.author', verbose_name='Подписчики продукта'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop'], name='price_check_shop_id_962424_idx'),
        ),
    ]
