# Generated by Django 5.1.6 on 2025-04-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_checker', '0033_remove_product_price_check_shop_id_2f705b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя продукта'),
        ),
    ]
