# Generated by Django 5.1.6 on 2025-04-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dest_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dest_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slots',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.CharField(choices=[('GOLD', 'Golden Status'), ('SILVER', 'Silver Status'), ('BRONZE', 'Bronze Status'), ('FREE', 'Free Status')], default='FREE', max_length=6),
        ),
    ]
