# Generated by Django 5.1.6 on 2025-05-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription',
            field=models.CharField(choices=[('ULTIMA', 'Ultima Status'), ('PLATINUM', 'Platinum Status'), ('FREE', 'Free Status')], default='FREE', max_length=8),
        ),
    ]
