# Generated by Django 5.1.6 on 2025-04-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_dest_id_customuser_dest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dest_id',
            field=models.CharField(default='123589280', max_length=100),
        ),
    ]
