# Generated by Django 5.1.6 on 2025-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discount_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slots',
            field=models.IntegerField(default=10),
        ),
    ]
