# Generated by Django 5.1.6 on 2025-06-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_discount_balance_alter_customuser_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_discount',
            field=models.IntegerField(default=10, verbose_name='Скидка для уведомления (%)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_discount_price',
            field=models.IntegerField(default=100, verbose_name='Скидка для уведомления (руб)'),
        ),
    ]
