# Generated by Django 5.1.6 on 2025-04-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_dest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dest_id',
            field=models.CharField(default='-1257786', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dest_name',
            field=models.CharField(default='Москва', max_length=1000),
        ),
    ]
