# Generated by Django 5.1.6 on 2025-06-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_notification_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pricedown_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='priceup_notification',
            field=models.BooleanField(default=True),
        ),
    ]
