# Generated by Django 5.1.6 on 2025-06-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_pricedown_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notification_discount_price',
            field=models.IntegerField(default=300, verbose_name='Скидка для уведомления (руб)'),
        ),
    ]
