# Generated by Django 5.2.3 on 2025-06-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_notification_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slots',
            field=models.IntegerField(default=20),
        ),
    ]
