# Generated by Django 5.2.3 on 2025-06-20 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_expire',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='SubRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('duration', models.DurationField()),
                ('sub_plan', models.CharField(choices=[('ULTIMA', 'Ultima Status'), ('PLATINUM', 'Platinum Status'), ('FREE', 'Free Status')], default='FREE', max_length=8)),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
