# Generated by Django 5.2.3 on 2025-06-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_sub_expire_subrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrequest',
            name='duration',
            field=models.CharField(default='1 month', max_length=8),
        ),
    ]
