# Generated by Django 5.2.3 on 2025-06-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_subrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
