# Generated by Django 5.2.3 on 2025-06-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_sub_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrequest',
            name='duration',
            field=models.CharField(default='1', max_length=8),
        ),
    ]
