# Generated by Django 5.2.3 on 2025-06-20 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_subrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 13, 35, 41, 717724, tzinfo=datetime.timezone.utc)),
        ),
    ]
