# Generated by Django 5.2.3 on 2025-06-20 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_subrequest_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrequest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
