# Generated by Django 5.2.3 on 2025-06-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_subrequest_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prods',
            field=models.IntegerField(default=0, verbose_name='Количество продуктов'),
        ),
    ]
