# Generated by Django 5.2.3 on 2025-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_telegramuser_customuser_tg_token_customuser_tg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='tg_id',
            field=models.BigIntegerField(),
        ),
    ]
