# Generated by Django 5.2.3 on 2025-07-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_telegramuser_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tg_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
