# Generated by Django 5.2.3 on 2025-07-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_tg_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tg_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_user', to='accounts.telegramuser'),
        ),
    ]
