version: '3.12.6'

services:
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py loaddata initial.json &&
             gunicorn project_x.wsgi:application --bind 0.0.0.0:8000 --workers 3 --preload --log-level info"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    command: celery -A project_x worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery-beat:
    build:
      context: .
    command: celery -A project_x beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:
