# Generated by Django 5.1.6 on 2025-05-13 23:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WBBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя бренда WB')),
                ('wb_id', models.IntegerField(unique=True, verbose_name='ID бренда WB')),
                ('main_url', models.URLField(blank=True, verbose_name='URL главной страницы')),
                ('subs', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подписчики бренда')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='WBCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.CharField(max_length=100, verbose_name='ID категории WB')),
                ('url', models.URLField(blank=True, verbose_name='URL категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'indexes': [models.Index(fields=['wb_id'], name='wb_checker__wb_id_33fbf3_idx')],
            },
        ),
        migrations.CreateModel(
            name='WBDetailedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_price', models.IntegerField(verbose_name='Цена продукта WB')),
                ('first_price', models.IntegerField(verbose_name='Первая цена продукта WB')),
                ('size', models.CharField(max_length=20, null=True, verbose_name='Размер')),
                ('volume', models.IntegerField(verbose_name='Количество')),
                ('enabled', models.BooleanField(default=True, verbose_name='Есть в наличии')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обновления продукта')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор продукта')),
            ],
            options={
                'verbose_name': 'Информация о продукте',
                'verbose_name_plural': 'Информация о продуктах',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='WBMenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Имя категории WB')),
                ('shard_key', models.CharField(max_length=1000, null=True, verbose_name='Ключ шардирования категории WB')),
                ('wb_id', models.IntegerField(unique=True, verbose_name='WB ID категории WB')),
                ('query', models.CharField(max_length=1000, null=True, verbose_name='Строка запроса к api')),
                ('main_url', models.URLField(null=True, verbose_name='URL категории')),
                ('parent', models.IntegerField(null=True, verbose_name='ID родительской категории')),
                ('ru_path', models.CharField(max_length=1000, null=True, verbose_name='RU путь с родительскими категориями')),
                ('subs', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подписчики категории')),
            ],
            options={
                'verbose_name': 'Категория меню WB',
                'verbose_name_plural': 'Категории меню WB',
            },
        ),
        migrations.CreateModel(
            name='WBPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена продукта WB')),
                ('added_time', models.DateTimeField(verbose_name='Добавлено')),
                ('detailed_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbdetailedinfo', verbose_name='Продукт WB')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ['added_time'],
            },
        ),
        migrations.CreateModel(
            name='WBProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта WB')),
                ('artikul', models.IntegerField(unique=True, verbose_name='Артикул продукта WB')),
                ('wb_cosh', models.BooleanField(default=True)),
                ('url', models.URLField(verbose_name='URL')),
                ('image_url', models.URLField(verbose_name='Ссылка на картинку')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbbrand', verbose_name='Бренд продукта WB')),
            ],
            options={
                'verbose_name': 'Продукт WB',
                'verbose_name_plural': 'Продукты WB',
            },
        ),
        migrations.AddField(
            model_name='wbdetailedinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbproduct', verbose_name='Продукт WB'),
        ),
        migrations.CreateModel(
            name='WBSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продавца WB')),
                ('wb_id', models.IntegerField(unique=True, verbose_name='ID продавца WB')),
                ('main_url', models.URLField(blank=True, verbose_name='URL главной страницы')),
                ('subs', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подпичсики селлера')),
            ],
            options={
                'verbose_name': 'Продавец WB',
                'verbose_name_plural': 'Продавцы WB',
            },
        ),
        migrations.AddField(
            model_name='wbproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbseller', verbose_name='Продавец продукта WB'),
        ),
        migrations.CreateModel(
            name='TopWBProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта WB')),
                ('artikul', models.IntegerField(verbose_name='Артикул продукта WB')),
                ('score', models.FloatField(verbose_name='Внутренний рейтинг топ продукта WB')),
                ('wb_cosh', models.BooleanField(default=True)),
                ('latest_price', models.IntegerField(verbose_name='Цена топ продукта WB')),
                ('true_discount', models.IntegerField(verbose_name='Честная скидка топ продукта WB')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('feedbacks', models.IntegerField(verbose_name='Отзывы')),
                ('url', models.URLField(verbose_name='URL')),
                ('image_url', models.URLField(verbose_name='URL картинки товара')),
                ('created', models.DateField(verbose_name='Время добавления топ продукта WB')),
                ('source', models.CharField(choices=[('BRAND', ' Бренд'), ('SELLER', 'Продавец'), ('CATEGORY', 'Категория')], max_length=8)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbbrand', verbose_name='Бренд продукта WB')),
                ('menu_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbmenucategory', verbose_name='Категория продукта WB')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbseller', verbose_name='Продавец продукта WB')),
            ],
            options={
                'verbose_name': 'Топ продукт WB',
                'verbose_name_plural': 'Топ продукты WB',
                'ordering': ['artikul'],
            },
        ),
        migrations.AddIndex(
            model_name='wbbrand',
            index=models.Index(fields=['wb_id'], name='wb_checker__wb_id_f7c03b_idx'),
        ),
        migrations.AddIndex(
            model_name='wbmenucategory',
            index=models.Index(fields=['wb_id'], name='wb_checker__wb_id_6f4032_idx'),
        ),
        migrations.AddIndex(
            model_name='wbprice',
            index=models.Index(fields=['detailed_info'], name='wb_checker__detaile_5c1c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='wbdetailedinfo',
            index=models.Index(fields=['product', 'author'], name='wb_checker__product_34f39b_idx'),
        ),
        migrations.AddConstraint(
            model_name='wbdetailedinfo',
            constraint=models.UniqueConstraint(fields=('product', 'latest_price', 'first_price', 'size', 'volume', 'enabled', 'updated', 'author'), name='total_repetition'),
        ),
        migrations.AddIndex(
            model_name='wbseller',
            index=models.Index(fields=['wb_id'], name='wb_checker__wb_id_53bbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='wbproduct',
            index=models.Index(fields=['artikul'], name='wb_checker__artikul_25d386_idx'),
        ),
        migrations.AddIndex(
            model_name='topwbproduct',
            index=models.Index(fields=['artikul'], name='wb_checker__artikul_44a813_idx'),
        ),
    ]
