# Generated by Django 5.1.6 on 2025-03-26 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0016_alter_author_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя бренда WB')),
                ('wb_id', models.CharField(max_length=100, verbose_name='ID бренда WB')),
                ('main_url', models.URLField(blank=True, verbose_name='URL главной страницы')),
                ('catalog_count', models.IntegerField(verbose_name='Всего товаров в каталоге бренда')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'indexes': [models.Index(fields=['name'], name='wb_checker__name_099548_idx')],
            },
        ),
        migrations.CreateModel(
            name='WBSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продавца WB')),
                ('wb_id', models.CharField(max_length=100, verbose_name='ID продавца WB')),
                ('main_url', models.URLField(blank=True, verbose_name='URL главной страницы')),
                ('catalog_count', models.IntegerField(verbose_name='Всего товаров в каталоге продавца')),
            ],
            options={
                'verbose_name': 'Продавец WB',
                'verbose_name_plural': 'Продавцы WB',
                'indexes': [models.Index(fields=['name'], name='wb_checker__name_37f309_idx')],
            },
        ),
        migrations.CreateModel(
            name='WBProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта WB')),
                ('artikul', models.CharField(max_length=100, verbose_name='Артикул продукта WB')),
                ('latest_price', models.IntegerField(verbose_name='Последняя цена')),
                ('wb_cosh', models.BooleanField(default=True)),
                ('url', models.URLField(verbose_name='URL')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления продукта WB')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обновления продукта WB')),
                ('authors', models.ManyToManyField(to='blog.author', verbose_name='Никнеймы авторов')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbbrand', verbose_name='Бренд продукта WB')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbseller', verbose_name='Продавец продукта WB')),
            ],
            options={
                'verbose_name': 'Продукт WB',
                'verbose_name_plural': 'Продукты WB',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='WBPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена продукта WB')),
                ('added_time', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbproduct', verbose_name='Продукт WB')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ['added_time'],
                'indexes': [models.Index(fields=['product'], name='wb_checker__product_ee18a1_idx')],
            },
        ),
    ]
