# Generated by Django 5.1.6 on 2025-04-26 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbbrand',
            name='subs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подписчики бренда'),
        ),
        migrations.AlterField(
            model_name='wbdetailedinfo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор продукта'),
        ),
        migrations.AlterField(
            model_name='wbmenucategory',
            name='subs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подписчики категории'),
        ),
        migrations.AlterField(
            model_name='wbseller',
            name='subs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подпичсики селлера'),
        ),
    ]
