# Generated by Django 5.1.6 on 2025-03-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0002_wbbrand_full_control_wbseller_full_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbbrand',
            name='catalog_count',
        ),
        migrations.RemoveField(
            model_name='wbseller',
            name='catalog_count',
        ),
    ]
