# Generated by Django 5.1.6 on 2025-05-07 12:16

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0002_remove_wbdetailedinfo_total_repetition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wbdetailedinfo',
            name='total_repetition',
        ),
        migrations.AddField(
            model_name='wbdetailedinfo',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обновления продукта'),
        ),
        migrations.AddConstraint(
            model_name='wbdetailedinfo',
            constraint=models.UniqueConstraint(fields=('product', 'latest_price', 'first_price', 'size', 'volume', 'enabled', 'updated', 'author'), name='total_repetition'),
        ),
    ]
