# Generated by Django 5.1.6 on 2025-04-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0002_alter_wbbrand_subs_alter_wbdetailedinfo_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbproduct',
            name='image_url',
            field=models.URLField(default='null', verbose_name='Ссылка на картинку'),
            preserve_default=False,
        ),
    ]
