# Generated by Django 5.1.6 on 2025-05-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0003_remove_wbdetailedinfo_total_repetition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wbdetailedinfo',
            options={'ordering': ['-updated'], 'verbose_name': 'Информация о продукте', 'verbose_name_plural': 'Информация о продуктах'},
        ),
    ]
