# Generated by Django 5.1.6 on 2025-04-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0003_wbproduct_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topwbproduct',
            name='image_url',
            field=models.URLField(default='null', verbose_name='URL картинки товара'),
            preserve_default=False,
        ),
    ]
