# Generated by Django 5.1.6 on 2025-06-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0004_alter_topwbproduct_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbdetailedinfo',
            name='last_notified_price',
            field=models.IntegerField(null=True, verbose_name='Цена уведомления пользователя'),
        ),
    ]
