# Generated by Django 5.1.6 on 2025-05-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0004_alter_wbdetailedinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topwbproduct',
            name='true_discount',
            field=models.IntegerField(default=1, verbose_name='Честная скидка топ продукта WB'),
            preserve_default=False,
        ),
    ]
