# Generated by Django 5.1.6 on 2025-03-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0004_alter_wbprice_added_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.CharField(max_length=100, verbose_name='ID категории WB')),
                ('main_url', models.URLField(blank=True, verbose_name='URL категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RemoveIndex(
            model_name='wbbrand',
            name='wb_checker__name_099548_idx',
        ),
        migrations.RemoveIndex(
            model_name='wbseller',
            name='wb_checker__name_37f309_idx',
        ),
        migrations.AddIndex(
            model_name='wbbrand',
            index=models.Index(fields=['wb_id'], name='wb_checker__wb_id_f7c03b_idx'),
        ),
        migrations.AddIndex(
            model_name='wbseller',
            index=models.Index(fields=['wb_id'], name='wb_checker__wb_id_53bbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='wbcategories',
            index=models.Index(fields=['wb_id'], name='wb_checker__wb_id_5448ed_idx'),
        ),
    ]
