# Generated by Django 5.1.6 on 2025-05-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0005_topwbproduct_true_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbmenucategory',
            name='parent',
            field=models.IntegerField(null=True, verbose_name='ID родительской категории'),
        ),
    ]
