# Generated by Django 5.1.6 on 2025-03-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0005_wbcategories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WBCategories',
            new_name='WBCategory',
        ),
        migrations.RenameIndex(
            model_name='wbcategory',
            new_name='wb_checker__wb_id_33fbf3_idx',
            old_name='wb_checker__wb_id_5448ed_idx',
        ),
    ]
