# Generated by Django 5.1.6 on 2025-06-11 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0005_wbdetailedinfo_last_notified_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbdetailedinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 11, 0, 43, 57, 926369, tzinfo=datetime.timezone.utc), verbose_name='Время добавления продукта'),
            preserve_default=False,
        ),
    ]
