# Generated by Django 5.1.6 on 2025-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0006_wbmenucategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbmenucategory',
            name='main_url',
            field=models.URLField(null=True, verbose_name='URL категории'),
        ),
        migrations.AlterField(
            model_name='wbmenucategory',
            name='query',
            field=models.CharField(max_length=300, null=True, verbose_name='Строка запроса к api'),
        ),
        migrations.AlterField(
            model_name='wbmenucategory',
            name='shard_key',
            field=models.CharField(max_length=50, null=True, verbose_name='Ключ шардирования категории WB'),
        ),
    ]
