# Generated by Django 5.1.6 on 2025-03-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0006_rename_wbcategories_wbcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wbcategory',
            old_name='main_url',
            new_name='url',
        ),
    ]
