# Generated by Django 5.2.3 on 2025-06-25 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0006_wbdetailedinfo_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wbbrand',
            options={'verbose_name': 'Бренд WB', 'verbose_name_plural': 'Бренды WB'},
        ),
        migrations.AlterField(
            model_name='wbseller',
            name='subs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подписчики селлера'),
        ),
    ]
