# Generated by Django 5.1.6 on 2025-03-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0007_rename_main_url_wbcategory_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbbrand',
            name='wb_id',
            field=models.IntegerField(verbose_name='ID бренда WB'),
        ),
        migrations.AlterField(
            model_name='wbseller',
            name='wb_id',
            field=models.IntegerField(verbose_name='ID продавца WB'),
        ),
    ]
