# Generated by Django 5.1.6 on 2025-05-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0007_alter_wbmenucategory_main_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbmenucategory',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Имя категории WB'),
        ),
        migrations.AlterField(
            model_name='wbmenucategory',
            name='query',
            field=models.CharField(max_length=1000, null=True, verbose_name='Строка запроса к api'),
        ),
        migrations.AlterField(
            model_name='wbmenucategory',
            name='shard_key',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ключ шардирования категории WB'),
        ),
    ]
