# Generated by Django 5.1.6 on 2025-05-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0008_alter_wbmenucategory_name_alter_wbmenucategory_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbmenucategory',
            name='ru_path',
            field=models.CharField(default=1, max_length=1000, verbose_name='RU путь с родительскими категориями'),
            preserve_default=False,
        ),
    ]
