# Generated by Django 5.1.6 on 2025-05-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0009_wbmenucategory_ru_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbmenucategory',
            name='ru_path',
            field=models.CharField(max_length=1000, null=True, verbose_name='RU путь с родительскими категориями'),
        ),
    ]
