# Generated by Django 5.1.6 on 2025-05-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0010_alter_wbmenucategory_ru_path'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wbdetailedinfo',
            managers=[
            ],
        ),
    ]
