# Generated by Django 5.1.6 on 2025-04-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0012_alter_wbproduct_artikul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbbrand',
            name='wb_id',
            field=models.IntegerField(unique=True, verbose_name='ID бренда WB'),
        ),
        migrations.AlterField(
            model_name='wbpromotion',
            name='wb_id',
            field=models.IntegerField(unique=True, verbose_name='ID промоации WB'),
        ),
        migrations.AlterField(
            model_name='wbseller',
            name='wb_id',
            field=models.IntegerField(unique=True, verbose_name='ID продавца WB'),
        ),
    ]
