# Generated by Django 5.1.6 on 2025-04-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_author_slots'),
        ('wb_checker', '0013_alter_wbbrand_wb_id_alter_wbpromotion_wb_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пресета')),
                ('main_url', models.URLField(unique=True, verbose_name='URL пресета')),
                ('authors', models.ManyToManyField(to='blog.author', verbose_name='Никнеймы авторов')),
            ],
        ),
        migrations.AddField(
            model_name='wbproduct',
            name='presets',
            field=models.ManyToManyField(to='wb_checker.wbpreset', verbose_name='Пресеты авторов'),
        ),
    ]
