# Generated by Django 5.1.6 on 2025-04-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_author_slots'),
        ('wb_checker', '0014_wbpreset_wbproduct_presets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbpreset',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='wbproduct',
            name='presets',
        ),
        migrations.AddField(
            model_name='wbpreset',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Никнеймы авторов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wbpreset',
            name='products',
            field=models.ManyToManyField(to='wb_checker.wbproduct', verbose_name='Продукты пресета'),
        ),
    ]
