# Generated by Django 5.1.6 on 2025-04-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0015_remove_wbpreset_authors_remove_wbproduct_presets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbpreset',
            name='max_elems',
            field=models.IntegerField(default=0, verbose_name='Количество продуктов, добавленных из пресета'),
        ),
    ]
