# Generated by Django 5.1.6 on 2025-04-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0016_wbpreset_max_elems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbpreset',
            name='main_url',
            field=models.URLField(verbose_name='URL пресета'),
        ),
    ]
