# Generated by Django 5.1.6 on 2025-04-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_author_slots'),
        ('wb_checker', '0017_alter_wbpreset_main_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbproduct',
            name='authors',
        ),
        migrations.AddField(
            model_name='wbproduct',
            name='disabled_authors',
            field=models.ManyToManyField(related_name='disabled_authors', to='blog.author', verbose_name='Никнеймы авторов (нет в наличии)'),
        ),
        migrations.AddField(
            model_name='wbproduct',
            name='enabled_authors',
            field=models.ManyToManyField(related_name='enabled_authors', to='blog.author', verbose_name='Никнеймы авторов'),
        ),
    ]
