# Generated by Django 5.1.6 on 2025-04-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0018_remove_wbproduct_authors_wbproduct_disabled_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbproduct',
            name='enabled',
        ),
    ]
