# Generated by Django 5.1.6 on 2025-04-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0020_remove_wbproduct_disabled_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbproduct',
            name='promotion',
        ),
        migrations.DeleteModel(
            name='WBPromotion',
        ),
    ]
