# Generated by Django 5.1.6 on 2025-04-08 22:35

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_author_slots'),
        ('wb_checker', '0022_alter_wbproduct_options_remove_wbproduct_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBDetailedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_price', models.IntegerField(verbose_name='Цена продукта WB')),
                ('size', models.CharField(max_length=20, null=True, verbose_name='Размер')),
                ('volume', models.IntegerField(verbose_name='Количество')),
                ('enabled', models.BooleanField(default=True, verbose_name='Есть в наличии')),
            ],
            options={
                'verbose_name': 'Информация о продукте',
                'verbose_name_plural': 'Информация о продуктах',
            },
            managers=[
                ('enabled_products', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='wbprice',
            name='wb_checker__product_ee18a1_idx',
        ),
        migrations.RemoveField(
            model_name='wbprice',
            name='product',
        ),
        migrations.AddField(
            model_name='wbdetailedinfo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Автор продукта'),
        ),
        migrations.AddField(
            model_name='wbdetailedinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbproduct', verbose_name='Продукт WB'),
        ),
        migrations.AddField(
            model_name='wbprice',
            name='detailed_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbdetailedinfo', verbose_name='Продукт WB'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='wbprice',
            index=models.Index(fields=['detailed_info'], name='wb_checker__detaile_5c1c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='wbdetailedinfo',
            index=models.Index(fields=['product', 'author'], name='wb_checker__product_34f39b_idx'),
        ),
    ]
