# Generated by Django 5.1.6 on 2025-04-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_author_slots'),
        ('wb_checker', '0023_wbdetailedinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopWBProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта WB')),
                ('artikul', models.IntegerField(unique=True, verbose_name='Артикул продукта WB')),
                ('score', models.FloatField(verbose_name='Внутренний рейтинг топ продукта WB')),
                ('wb_cosh', models.BooleanField(default=True)),
                ('latest_price', models.IntegerField(verbose_name='Цена топ продукта WB')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('feedbacks', models.IntegerField(verbose_name='Отзывы')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Топ продукт WB',
                'verbose_name_plural': 'Топ продукты WB',
            },
        ),
        migrations.AddConstraint(
            model_name='wbdetailedinfo',
            constraint=models.UniqueConstraint(fields=('product', 'latest_price', 'size', 'volume', 'enabled', 'author'), name='total_repetition'),
        ),
        migrations.AddField(
            model_name='topwbproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbbrand', verbose_name='Бренд продукта WB'),
        ),
        migrations.AddField(
            model_name='topwbproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbseller', verbose_name='Продавец продукта WB'),
        ),
        migrations.AddIndex(
            model_name='topwbproduct',
            index=models.Index(fields=['artikul'], name='wb_checker__artikul_44a813_idx'),
        ),
    ]
