# Generated by Django 5.1.6 on 2025-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_author_slots'),
        ('wb_checker', '0023_wbdetailedinfo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wbdetailedinfo',
            constraint=models.UniqueConstraint(fields=('product', 'latest_price', 'size', 'volume', 'enabled', 'author'), name='total_repetition'),
        ),
    ]
