# Generated by Django 5.1.6 on 2025-04-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0024_wbdetailedinfo_total_repetition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopWBProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта WB')),
                ('artikul', models.IntegerField(unique=True, verbose_name='Артикул продукта WB')),
                ('score', models.FloatField(verbose_name='Внутренний рейтинг топ продукта WB')),
                ('wb_cosh', models.BooleanField(default=True)),
                ('latest_price', models.IntegerField(verbose_name='Цена топ продукта WB')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('feedbacks', models.IntegerField(verbose_name='Отзывы')),
                ('url', models.URLField(verbose_name='URL')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbbrand', verbose_name='Бренд продукта WB')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbseller', verbose_name='Продавец продукта WB')),
            ],
            options={
                'verbose_name': 'Топ продукт WB',
                'verbose_name_plural': 'Топ продукты WB',
                'indexes': [models.Index(fields=['artikul'], name='wb_checker__artikul_44a813_idx')],
            },
        ),
    ]
