# Generated by Django 5.1.6 on 2025-04-14 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_author_slots'),
        ('wb_checker', '0025_topwbproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbbrand',
            name='full_control',
        ),
        migrations.RemoveField(
            model_name='wbseller',
            name='full_control',
        ),
        migrations.AddField(
            model_name='topwbproduct',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Время добавления топ продукта WB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wbbrand',
            name='subs',
            field=models.ManyToManyField(to='blog.author', verbose_name='Подписчики бренда'),
        ),
        migrations.AddField(
            model_name='wbseller',
            name='subs',
            field=models.ManyToManyField(to='blog.author', verbose_name='Подпичсики селлера'),
        ),
    ]
