# Generated by Django 5.1.6 on 2025-04-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0026_remove_wbbrand_full_control_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WBPreset',
        ),
    ]
