# Generated by Django 5.1.6 on 2025-04-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0027_delete_wbpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='topwbproduct',
            name='source',
            field=models.CharField(choices=[('BRAND', ' Бренд'), ('SELLER', 'Продавец'), ('CATEGORY', 'Категория')], default='BRAND', max_length=8),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='topwbproduct',
            constraint=models.UniqueConstraint(fields=('artikul', 'source'), name='source_repetition'),
        ),
    ]
