# Generated by Django 5.1.6 on 2025-04-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0028_topwbproduct_source_topwbproduct_source_repetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topwbproduct',
            name='artikul',
            field=models.IntegerField(verbose_name='Артикул продукта WB'),
        ),
    ]
