# Generated by Django 5.1.6 on 2025-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_author_subscription'),
        ('wb_checker', '0029_alter_topwbproduct_artikul'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBMenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя категории WB')),
                ('shard_key', models.IntegerField(verbose_name='Ключ шардирования категории WB')),
                ('wb_id', models.IntegerField(unique=True, verbose_name='WB ID категории WB')),
                ('main_url', models.URLField(blank=True, verbose_name='URL категории')),
                ('subs', models.ManyToManyField(to='blog.author', verbose_name='Подписчики категории')),
            ],
            options={
                'verbose_name': 'Продавец WB',
                'verbose_name_plural': 'Продавцы WB',
                'indexes': [models.Index(fields=['wb_id'], name='wb_checker__wb_id_6f4032_idx')],
            },
        ),
    ]
