# Generated by Django 5.1.6 on 2025-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0030_wbmenucategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbmenucategory',
            name='shard_key',
            field=models.CharField(max_length=50, verbose_name='Ключ шардирования категории WB'),
        ),
    ]
