# Generated by Django 5.1.6 on 2025-04-15 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0031_alter_wbmenucategory_shard_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='topwbproduct',
            name='menu_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbmenucategory', verbose_name='Категория продукта WB'),
        ),
    ]
