# Generated by Django 5.1.6 on 2025-04-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0032_topwbproduct_menu_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wbmenucategory',
            options={'verbose_name': 'Категория меню WB', 'verbose_name_plural': 'Категории меню WB'},
        ),
        migrations.AddField(
            model_name='wbmenucategory',
            name='query',
            field=models.CharField(default='null', max_length=50, verbose_name='Строка запроса к api'),
            preserve_default=False,
        ),
    ]
