# Generated by Django 5.1.6 on 2025-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0033_alter_wbmenucategory_options_wbmenucategory_query'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='topwbproduct',
            name='source_repetition',
        ),
        migrations.AddConstraint(
            model_name='topwbproduct',
            constraint=models.UniqueConstraint(fields=('artikul', 'source', 'menu_category'), name='source_repetition'),
        ),
    ]
