# Generated by Django 5.1.6 on 2025-04-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0034_remove_topwbproduct_source_repetition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topwbproduct',
            options={'ordering': ['artikul'], 'verbose_name': 'Топ продукт WB', 'verbose_name_plural': 'Топ продукты WB'},
        ),
    ]
