# Generated by Django 5.1.6 on 2025-04-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0035_alter_topwbproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbmenucategory',
            name='shard_key',
            field=models.CharField(max_length=150, verbose_name='Ключ шардирования категории WB'),
        ),
    ]
