# Generated by Django 5.1.6 on 2025-04-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0036_alter_wbmenucategory_shard_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbmenucategory',
            name='query',
            field=models.CharField(max_length=150, verbose_name='Строка запроса к api'),
        ),
        migrations.AlterField(
            model_name='wbmenucategory',
            name='shard_key',
            field=models.CharField(max_length=50, verbose_name='Ключ шардирования категории WB'),
        ),
    ]
