# Generated by Django 5.1.6 on 2025-04-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0037_alter_wbmenucategory_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbmenucategory',
            name='query',
            field=models.CharField(max_length=200, verbose_name='Строка запроса к api'),
        ),
    ]
