# Generated by Django 5.1.6 on 2025-04-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_checker', '0038_alter_wbmenucategory_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbmenucategory',
            name='query',
            field=models.CharField(max_length=300, verbose_name='Строка запроса к api'),
        ),
    ]
