# Generated by Django 5.1.6 on 2025-06-06 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_checker', '0005_product_repeated'),
        ('wb_checker', '0004_alter_topwbproduct_menu_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Текст уведомления')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время уведомления')),
                ('additional_link', models.URLField(null=True, verbose_name='Доп. ссылка')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='price_checker.product', verbose_name='Обычный продукт')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('wb_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbdetailedinfo', verbose_name='WB продукт')),
            ],
        ),
    ]
