# Generated by Django 5.1.6 on 2025-06-07 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wb_checker', '0005_wbdetailedinfo_last_notified_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='wb_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wb_checker.wbdetailedinfo', verbose_name='WB продукт'),
        ),
    ]
