# Generated by Django 5.1.6 on 2025-06-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_wb_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст уведомления')),
                ('time', models.DateField(auto_now_add=True, verbose_name='Дата уведомления')),
            ],
        ),
    ]
