# Generated by Django 5.1.6 on 2025-06-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=256, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
