# Generated by Django 5.1.6 on 2025-02-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Введите название поста', max_length=120, verbose_name='Название поста')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('text', models.TextField(help_text='Введите текст поста', verbose_name='Полный текст поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('fixed', models.BooleanField(default=False, verbose_name='Прикреплено')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created'],
            },
        ),
    ]
