# Generated by Django 5.1.6 on 2025-04-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='Никнейм')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('subscription', models.CharField(choices=[('GOLD', 'Golden Status'), ('SILVER', 'Silver Status'), ('BRONZE', 'Bronze Status'), ('FREE', 'Free Status')], default='FREE', max_length=6)),
                ('slots', models.IntegerField(default=1000)),
                ('dest_name', models.CharField(max_length=1000, null=True)),
                ('dest_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Введите название поста', max_length=120, verbose_name='Название поста')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('text', models.TextField(help_text='Введите текст поста', verbose_name='Полный текст поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('fixed', models.BooleanField(default=False, verbose_name='Прикреплено')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.author')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created'],
                'abstract': False,
                'proxy': False,
            },
        ),
    ]
