# Generated by Django 5.1.6 on 2025-02-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='not-added', max_length=80, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
