# Generated by Django 5.1.6 on 2025-03-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_author_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['nickname'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
    ]
