# Generated by Django 5.1.6 on 2025-03-12 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_author_options_alter_author_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['age'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
