# Generated by Django 5.1.6 on 2025-03-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_author_options_alter_author_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='subscription',
            field=models.CharField(choices=[('GL', 'Golden Status'), ('SL', 'Silver Status'), ('BR', 'Bronze Status'), ('FR', 'Free Status')], default='FR', max_length=100),
        ),
    ]
