# Generated by Django 5.1.6 on 2025-04-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_author_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dest',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
