# Generated by Django 5.1.6 on 2025-04-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_author_dest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='dest',
            new_name='dest_id',
        ),
        migrations.AddField(
            model_name='author',
            name='dest_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
