# Generated by Django 5.1.6 on 2025-04-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_dest_author_dest_id_author_dest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slots',
            field=models.IntegerField(default=1000),
        ),
    ]
