# Generated by Django 5.1.6 on 2025-04-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_author_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='subscription',
            field=models.CharField(choices=[('GOLD', 'Golden Status'), ('SILVER', 'Silver Status'), ('BRONZE', 'Bronze Status'), ('FREE', 'Free Status')], default='FREE', max_length=50),
        ),
    ]
