# Generated by Django 5.1.6 on 2025-04-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя теста')),
                ('text', models.TextField(verbose_name='Текст теста')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('best_result', models.IntegerField(default=0, verbose_name='Лучший результат')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('answer1', models.CharField(max_length=2000, null=True, verbose_name='Ответ 1')),
                ('answer2', models.CharField(max_length=2000, null=True, verbose_name='Ответ 2')),
                ('answer3', models.CharField(max_length=2000, null=True, verbose_name='Ответ 3')),
                ('right_answer', models.CharField(max_length=10, null=True, verbose_name='Правильный ответ')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_generator.test', verbose_name='Имя теста')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
