# Generated by Django 5.1.6 on 2025-03-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer1',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer2',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer3',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='right_answer',
            field=models.IntegerField(null=True),
        ),
    ]
