# Generated by Django 5.1.6 on 2025-03-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator', '0002_question_answer1_question_answer2_question_answer3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
