# Generated by Django 5.1.6 on 2025-03-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator', '0004_test_best_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
