# Generated by Django 5.1.6 on 2025-03-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator', '0005_alter_test_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=models.CharField(max_length=2000, null=True, verbose_name='Ответ 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(max_length=2000, null=True, verbose_name='Ответ 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(max_length=2000, null=True, verbose_name='Ответ 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.CharField(max_length=10, null=True, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='test',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='test',
            name='best_result',
            field=models.IntegerField(default=0, verbose_name='Лучший результат'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='text',
            field=models.TextField(verbose_name='Текст теста'),
        ),
    ]
