# Generated by Django 5.1.6 on 2025-03-12 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator', '0006_alter_question_options_alter_test_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_generator.test', verbose_name='Имя теста'),
        ),
    ]
